### ISSUE TITLE
Exception: Argument too large: value

### ISSUE THREAD

**Issue by shojimeguro** [techstreams/TSDataTable#3]
when script launched on 500 rows of table, it will shows : Exception: Argument too large: value

please increase the script timeout so it can be used to run more time.

**Comment by techstreams** [comment]
Thanks for the comment.  As noted in the documentation, TSDataTable is not meant to be used with large data sets. If you receive errors for exceeding the cache quota or the table takes to long to load, you may need a more robust solution.
